# Generated by Django 5.2.8 on 2025-11-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('por_vencer', 'Por Vencer'), ('vencido', 'Vencido')], default='vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_chasis',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_motor',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='documentovehiculo',
            name='tipo',
            field=models.CharField(choices=[('soat', 'SOAT'), ('rec', 'REC'), ('matricula', 'Matrícula'), ('revision', 'Revisión Técnica'), ('circulacion', 'Permiso de Circulación'), ('seguro', 'Seguro'), ('documentacion', 'Documentación Vehicular'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('mecanico', 'Mecánico'), ('electrico', 'Eléctrico'), ('otro', 'Otro')], max_length=20),
        ),
    ]
