# Generated by Django 5.2.8 on 2025-11-22 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pasajero'),
        ('viajes', '0002_remove_viaje_distancia_km_viaje_latitud_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajePasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pasajero')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Pasajero en Viaje',
                'verbose_name_plural': 'Pasajeros en Viajes',
                'unique_together': {('viaje', 'pasajero')},
            },
        ),
        migrations.AddField(
            model_name='viaje',
            name='pasajeros',
            field=models.ManyToManyField(blank=True, related_name='viajes', through='viajes.ViajePasajero', to='core.pasajero'),
        ),
    ]
