# Generated by Django 5.2.8 on 2025-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosviaje',
            name='combustible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
