# Generated by Django 5.2.8 on 2025-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_alter_costosviaje_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosviaje',
            name='combustible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='mantenimiento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='otros_costos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='costosviaje',
            name='peajes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
